# Copyright(c) 2021 aasaam software development group
version: "3"

services:
  app-dev-backend:
    container_name: app-backend
    image: node:15-stretch-slim
    working_dir: /app/backend
    ports:
      - ${ASM_APP_PORT:-3001}:${ASM_APP_PORT:-3001}
    volumes:
      - ./app/backend:/app/backend
      - ./tmp/.npm:/root/.npm
    environment:
      ASM_PUBLIC_APP_TEST: "true"
    command: tail -f /dev/null

  app-dev-frontend:
    container_name: app-frontend
    image: node:15-stretch-slim
    working_dir: /app/frontend
    ports:
      - 3000:3000
    volumes:
      - ./app/frontend:/app/frontend
      - ./tmp/.npm:/root/.npm
    command: tail -f /dev/null

  app-dev-redis:
    container_name: app-redis
    ports:
      - 6379:6379
    image: redis:6

  app-dev-nginx:
    container_name: app-nginx
    image: nginx:1
    ports:
      - 80:80
      - 443:443
    environment:
      ASM_NGINX_WORKER_PROCESSES: ${ASM_NGINX_WORKER_PROCESSES:-2}
      ASM_NGINX_WORKER_RLIMIT_NOFILE: ${ASM_NGINX_WORKER_RLIMIT_NOFILE:-1024}
      ASM_NGINX_WORKER_CONNECTIONS: ${ASM_NGINX_WORKER_CONNECTIONS:-512}
      ASM_NGINX_ERROR_LOG_LEVEL: ${ASM_NGINX_ERROR_LOG_LEVEL:-warn}
      ASM_NGINX_TMPFS_CACHE_SIZE_MB: ${ASM_NGINX_TMPFS_CACHE_SIZE_MB:-128}
      ASM_APP_PORT: ${ASM_APP_PORT:-3001}
      ASM_PUBLIC_BACKEND_PREFIX: ${ASM_PUBLIC_BACKEND_PREFIX:-/api}
    tmpfs:
      - /nginx-tmpfs:rw,nodev,nosuid,noexec,noatime,size=${ASM_NGINX_TMPFS_CACHE_SIZE_MB:-192}m
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - ./nginx/templates/default.dev.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/cert-local:/cert:ro
